version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
    - ./config.txt:/app/config.txt
    - ${PWD}/serversettings.json:/app/serversettings.json
