version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./config.txt:/app/config.txt
    - serversettings:/app/serversettings.json

volumes:
  serversettings:
